const backgroundOptions = [
	{id: 'Abrams', label: 'Abrams', file: 'Abrams_select_background.png'},
	{id: 'Apollo', label: 'Apollo', file: 'Apollo_select_background.png'},
	{id: 'Bebop', label: 'Bebop', file: 'Bebop_select_background.png'},
	{id: 'Billy', label: 'Billy', file: 'Billy_select_background.png'},
	{id: 'Calico', label: 'Calico', file: 'Calico_select_background.png'},
	{id: 'Celeste', label: 'Celeste', file: 'Celeste_select_background.png'},
	{id: 'Doorman', label: 'Doorman', file: 'Doorman_select_background.png'},
	{id: 'Drifter', label: 'Drifter', file: 'Drifter_select_background.png'},
	{id: 'Dynamo', label: 'Dynamo', file: 'Dynamo_select_background.png'},
	{id: 'Geist', label: 'Geist', file: 'Geist_select_background.png'},
	{id: 'Graves', label: 'Graves', file: 'Graves_select_background.png'},
	{id: 'Greytalon', label: 'Greytalon', file: 'Greytalon_select_background.png'},
	{id: 'Haze', label: 'Haze', file: 'Haze_select_background.png'},
	{id: 'Holliday', label: 'Holliday', file: 'Holliday_select_background.png'},
	{id: 'Infernus', label: 'Infernus', file: 'Infernus_select_background.png'},
	{id: 'Ivy', label: 'Ivy', file: 'Ivy_select_background.png'},
	{id: 'Kelvin', label: 'Kelvin', file: 'Kelvin_select_background.png'},
	{id: 'Krill', label: 'Krill', file: 'Krill_select_background.png'},
	{id: 'Lash', label: 'Lash', file: 'Lash_select_background.png'},
	{id: 'Mcginnis', label: 'Mcginnis', file: 'Mcginnis_select_background.png'},
	{id: 'Mina', label: 'Mina', file: 'Mina_select_background.png'},
	{id: 'Mirage', label: 'Mirage', file: 'Mirage_select_background.png'},
	{id: 'Paige', label: 'Paige', file: 'Paige_select_background.png'},
	{id: 'Paradox', label: 'Paradox', file: 'Paradox_select_background.png'},
	{id: 'Pocket', label: 'Pocket', file: 'Pocket_select_background.png'},
	{id: 'Rem', label: 'Rem', file: 'Rem_select_background.png'},
	{id: 'Seven', label: 'Seven', file: 'Seven_select_background.png'},
	{id: 'Shiv', label: 'Shiv', file: 'Shiv_select_background.png'},
	{id: 'Silver', label: 'Silver', file: 'Silver_select_background.png'},
	{id: 'Sinclair', label: 'Sinclair', file: 'Sinclair_select_background.png'},
	{id: 'Venator', label: 'Venator', file: 'Venator_select_background.png'},
	{id: 'Victor', label: 'Victor', file: 'Victor_select_background.png'},
	{id: 'Vindicta', label: 'Vindicta', file: 'Vindicta_select_background.png'},
	{id: 'Viscous', label: 'Viscous', file: 'Viscous_select_background.png'},
	{id: 'Vyper', label: 'Vyper', file: 'Vyper_select_background.png'},
	{id: 'Warden', label: 'Warden', file: 'Warden_select_background.png'},
	{id: 'Wraith', label: 'Wraith', file: 'Wraith_select_background.png'},
	{id: 'Yamato', label: 'Yamato', file: 'Yamato_select_background.png'},
];

const defaultBackgroundId = backgroundOptions[0].id;

export {backgroundOptions, defaultBackgroundId};