const abilityLibraryGroups = [
  { hero: 'abrams', icons: [
    'abrams/1.png',
    'abrams/2.png',
    'abrams/3.png',
    'abrams/4.png',
  ] },
  { hero: 'astro', icons: [
    'astro/1.png',
    'astro/2.png',
    'astro/3.png',
    'astro/4.png',
    'astro/gravity_lasso_psd.png',
    'astro/shotgun_psd.png',
  ] },
  { hero: 'bebop', icons: [
    'bebop/1.png',
    'bebop/2.png',
    'bebop/3.png',
    'bebop/4.png',
  ] },
  { hero: 'bookworm', icons: [
    'bookworm/1.png',
    'bookworm/2.png',
    'bookworm/3.png',
    'bookworm/4.png',
  ] },
  { hero: 'chrono', icons: [
    'chrono/1.png',
    'chrono/2.png',
    'chrono/3.png',
    'chrono/4.png',
  ] },
  { hero: 'doorman', icons: [
    'doorman/1.png',
    'doorman/2.png',
    'doorman/3.png',
    'doorman/4.png',
    'doorman/doorman_doorway2_psd.png',
    'doorman/doorman_doorwayclose_psd.png',
  ] },
  { hero: 'drifter', icons: [
    'drifter/1.png',
    'drifter/2.png',
    'drifter/3.png',
    'drifter/4.png',
    'drifter/drifter_terror_psd.png',
    'drifter/stalkers_mark_teleport_psd.png',
  ] },
  { hero: 'familiar', icons: [
    'familiar/1.png',
    'familiar/2.png',
    'familiar/3.png',
    'familiar/4.png',
    'familiar/familiar_tag_along2_psd.png',
  ] },
  { hero: 'fencer', icons: [
    'fencer/1.png',
    'fencer/2.png',
    'fencer/3.png',
    'fencer/4.png',
  ] },
  { hero: 'frank', icons: [
    'frank/1.png',
    'frank/2.png',
    'frank/3.png',
    'frank/4.png',
  ] },
  { hero: 'grappler', icons: [
    'grappler/1.png',
    'grappler/2.png',
    'grappler/3.png',
    'grappler/4.png',
  ] },
  { hero: 'grey_talon', icons: [
    'grey_talon/1.png',
    'grey_talon/2.png',
    'grey_talon/3.png',
    'grey_talon/4.png',
  ] },
  { hero: 'haze', icons: [
    'haze/1.png',
    'haze/2.png',
    'haze/3.png',
    'haze/4.png',
  ] },
  { hero: 'hornet', icons: [
    'hornet/1.png',
    'hornet/2.png',
    'hornet/3.png',
    'hornet/4.png',
  ] },
  { hero: 'infernus', icons: [
    'infernus/1.png',
    'infernus/2.png',
    'infernus/3.png',
    'infernus/4.png',
    'infernus/inferno_passive_psd.png',
  ] },
  { hero: 'kelvin', icons: [
    'kelvin/1.png',
    'kelvin/2.png',
    'kelvin/3.png',
    'kelvin/4.png',
  ] },
  { hero: 'lash', icons: [
    'lash/1.png',
    'lash/2.png',
    'lash/3.png',
    'lash/4.png',
  ] },
  { hero: 'magician', icons: [
    'magician/1.png',
    'magician/2.png',
    'magician/3.png',
    'magician/4.png',
  ] },
  { hero: 'mcginnis', icons: [
    'mcginnis/1.png',
    'mcginnis/2.png',
    'mcginnis/3.png',
    'mcginnis/4.png',
    'mcginnis/engineer_fissure_2_activate_psd.png',
  ] },
  { hero: 'mirage', icons: [
    'mirage/1.png',
    'mirage/2.png',
    'mirage/3.png',
    'mirage/4.png',
    'mirage/mirage_djinns_reach_psd.png',
    'mirage/mirage_sunfire_cataclysm_psd.png',
  ] },
  { hero: 'nano', icons: [
    'nano/1.png',
    'nano/2.png',
    'nano/3.png',
    'nano/4.png',
    'nano/nano_replicate_psd.png',
    'nano/nano_roller_bomb_psd.png',
    'nano/nano_tunnel_vision_psd.png',
    'nano/nano_warp_psd.png',
  ] },
  { hero: 'necro', icons: [
    'necro/1.png',
    'necro/2.png',
    'necro/3.png',
    'necro/4.png',
    'necro/necro_coffin_psd.png',
  ] },
  { hero: 'priest', icons: [
    'priest/1.png',
    'priest/2.png',
    'priest/3.png',
    'priest/4.png',
  ] },
  { hero: 'punkgoat', icons: [
    'punkgoat/1.png',
    'punkgoat/2.png',
    'punkgoat/3.png',
    'punkgoat/4.png',
    'punkgoat/punkgoat_capricious_psd.png',
  ] },
  { hero: 'seven', icons: [
    'seven/1.png',
    'seven/2.png',
    'seven/3.png',
    'seven/4.png',
  ] },
  { hero: 'shiv', icons: [
    'shiv/1.png',
    'shiv/2.png',
    'shiv/3.png',
    'shiv/4.png',
    'shiv/shiv_gather_foes_psd.png',
    'shiv/shiv_prison_dance_psd.png',
    'shiv/shiv_trophy_kill_psd.png',
  ] },
  { hero: 'slork', icons: [
    'slork/slork_invis_psd.png',
    'slork/slork_scald_psd.png',
  ] },
  { hero: 'spectre', icons: [
    'spectre/1.png',
    'spectre/2.png',
    'spectre/3.png',
    'spectre/4.png',
    'spectre/death_tax_psd.png',
  ] },
  { hero: 'sumo', icons: [
    'sumo/1.png',
    'sumo/2.png',
    'sumo/3.png',
    'sumo/4.png',
    'sumo/sumo_charge_psd.png',
  ] },
  { hero: 'synth', icons: [
    'synth/1.png',
    'synth/2.png',
    'synth/3.png',
    'synth/4.png',
    'synth/synth_grasp_psd.png',
  ] },
  { hero: 'tengu', icons: [
    'tengu/1.png',
    'tengu/2.png',
    'tengu/3.png',
    'tengu/4.png',
  ] },
  { hero: 'unicorn', icons: [
    'unicorn/1.png',
    'unicorn/2.png',
    'unicorn/3.png',
    'unicorn/4.png',
  ] },
  { hero: 'vampirebat', icons: [
    'vampirebat/1.png',
    'vampirebat/2.png',
    'vampirebat/3.png',
    'vampirebat/4.png',
    'vampirebat/love_bites_psd.png',
  ] },
  { hero: 'viper', icons: [
    'viper/1.png',
    'viper/2.png',
    'viper/3.png',
    'viper/4.png',
  ] },
  { hero: 'viscous', icons: [
    'viscous/1.png',
    'viscous/2.png',
    'viscous/3.png',
    'viscous/4.png',
    'viscous/viscous_goo_puddle_psd.png',
  ] },
  { hero: 'warden', icons: [
    'warden/1.png',
    'warden/2.png',
    'warden/3.png',
    'warden/4.png',
  ] },
  { hero: 'werewolf', icons: [
    'werewolf/1.png',
    'werewolf/2.png',
    'werewolf/3.png',
    'werewolf/4.png',
    'werewolf/werewolf_bite_psd.png',
    'werewolf/werewolf_tailwhack_psd.png',
    'werewolf/werewolf_wolfforward_psd.png',
  ] },
  { hero: 'wraith', icons: [
    'wraith/1.png',
    'wraith/2.png',
    'wraith/3.png',
    'wraith/4.png',
    'wraith/wraith_daggers_psd.png',
  ] },
  { hero: 'yamato', icons: [
    'yamato/1.png',
    'yamato/2.png',
    'yamato/3.png',
    'yamato/4.png',
  ] },
];

export {abilityLibraryGroups};
