// Minimal canonical hero list: id and display label only.
const heroAssets = [
	{id: 'Abrams', label: 'Abrams'},
	{id: 'Apollo', label: 'Apollo'},
	{id: 'Bebop', label: 'Bebop'},
	{id: 'Billy', label: 'Billy'},
	{id: 'Calico', label: 'Calico'},
	{id: 'Celeste', label: 'Celeste'},
	{id: 'Doorman', label: 'Doorman'},
	{id: 'Drifter', label: 'Drifter'},
	{id: 'Dynamo', label: 'Dynamo'},
	{id: 'Graves', label: 'Graves'},
	{id: 'GreyTalon', label: 'Grey Talon'},
	{id: 'Haze', label: 'Haze'},
	{id: 'Holliday', label: 'Holliday'},
	{id: 'Infernus', label: 'Infernus'},
	{id: 'Ivy', label: 'Ivy'},
	{id: 'Kelvin', label: 'Kelvin'},
	{id: 'LadyGeist', label: 'Lady Geist'},
	{id: 'Lash', label: 'Lash'},
	{id: 'McGinnis', label: 'McGinnis'},
	{id: 'Mina', label: 'Mina'},
	{id: 'Mirage', label: 'Mirage'},
	{id: 'MoKrill', label: 'Mo & Krill'},
	{id: 'Paige', label: 'Paige'},
	{id: 'Paradox', label: 'Paradox'},
	{id: 'Pocket', label: 'Pocket'},
	{id: 'Rem', label: 'Rem'},
	{id: 'Seven', label: 'Seven'},
	{id: 'Shiv', label: 'Shiv'},
	{id: 'Silver', label: 'Silver'},
	{id: 'Sinclair', label: 'Sinclair'},
	{id: 'Venator', label: 'Venator'},
	{id: 'Victor', label: 'Victor'},
	{id: 'Vindicta', label: 'Vindicta'},
	{id: 'Viscous', label: 'Viscous'},
	{id: 'Vyper', label: 'Vyper'},
	{id: 'Warden', label: 'Warden'},
	{id: 'Wraith', label: 'Wraith'},
	{id: 'Yamato', label: 'Yamato'},
];

export {heroAssets};