const heroAssets = [
	{id: 'Abrams', label: 'Abrams', portrait: 'portrait/Abrams_card.png', render: 'render/Abrams_Render.png', signature: 'signature/Abrams_name.png'},
	{id: 'Apollo', label: 'Apollo', portrait: 'portrait/Apollo_card.png', render: 'render/Apollo_Render.png', signature: 'signature/Apollo_name.png'},
	{id: 'Bebop', label: 'Bebop', portrait: 'portrait/Bebop_card.png', render: 'render/Bebop_Render.png', signature: 'signature/Bebop_name.png'},
	{id: 'Billy', label: 'Billy', portrait: 'portrait/Billy_card.png', render: 'render/Billy_Render.png', signature: 'signature/Billy_name.png'},
	{id: 'Calico', label: 'Calico', portrait: 'portrait/Calico_card.png', render: 'render/Calico_Render.png', signature: 'signature/Calico_name.png'},
	{id: 'Celeste', label: 'Celeste', portrait: 'portrait/Celeste_card.png', render: 'render/Celeste_Render.png', signature: 'signature/Celeste_name.png'},
	{id: 'Doorman', label: 'Doorman', portrait: 'portrait/The_Doorman_card.png', render: 'render/The_Doorman_Render.png', signature: 'signature/The_Doorman_name.png'},
	{id: 'Drifter', label: 'Drifter', portrait: 'portrait/Drifter_card.png', render: 'render/Drifter_Render.png', signature: 'signature/Drifter_name.png'},
	{id: 'Dynamo', label: 'Dynamo', portrait: 'portrait/Dynamo_card.png', render: 'render/Dynamo_Render.png', signature: 'signature/Dynamo_name.png'},
	{id: 'Graves', label: 'Graves', portrait: 'portrait/Graves_card.png', render: 'render/Graves_Render.png', signature: 'signature/Graves_name.png'},
	{id: 'GreyTalon', label: 'Grey Talon', portrait: 'portrait/Grey_Talon_card.png', render: 'render/Grey_Talon_Render.png', signature: 'signature/Grey_Talon_name.png'},
	{id: 'Haze', label: 'Haze', portrait: 'portrait/Haze_card.png', render: 'render/Haze_Render.png', signature: 'signature/Haze_name.png'},
	{id: 'Holliday', label: 'Holliday', portrait: 'portrait/Holliday_card.png', render: 'render/Holliday_Render.png', signature: 'signature/Holliday_name.png'},
	{id: 'Infernus', label: 'Infernus', portrait: 'portrait/Infernus_card.png', render: 'render/Infernus_Render.png', signature: 'signature/Infernus_name.png'},
	{id: 'Ivy', label: 'Ivy', portrait: 'portrait/Ivy_card.png', render: 'render/Ivy_Render.png', signature: 'signature/Ivy_name.png'},
	{id: 'Kelvin', label: 'Kelvin', portrait: 'portrait/Kelvin_card.png', render: 'render/Kelvin_Render.png', signature: 'signature/Kelvin_name.png'},
	{id: 'LadyGeist', label: 'Lady Geist', portrait: 'portrait/Lady_Geist_card.png', render: 'render/Lady_Geist_Render.png', signature: 'signature/Lady_Geist_name.png'},
	{id: 'Lash', label: 'Lash', portrait: 'portrait/Lash_card.png', render: 'render/Lash_Render.png', signature: 'signature/Lash_name.png'},
	{id: 'McGinnis', label: 'McGinnis', portrait: 'portrait/McGinnis_card.png', render: 'render/McGinnis_Render.png', signature: 'signature/McGinnis_name.png'},
	{id: 'Mina', label: 'Mina', portrait: 'portrait/Mina_card.png', render: 'render/Mina_Render.png', signature: 'signature/Mina_name.png'},
	{id: 'Mirage', label: 'Mirage', portrait: 'portrait/Mirage_card.png', render: 'render/Mirage_Render.png', signature: 'signature/Mirage_name.png'},
	{id: 'MoKrill', label: 'Mo & Krill', portrait: 'portrait/Mo_&_Krill_card.png', render: 'render/Mo_&_Krill_Render.png', signature: 'signature/Mo_&_Krill_name.png'},
	{id: 'Paige', label: 'Paige', portrait: 'portrait/Paige_card.png', render: 'render/Paige_Render.png', signature: 'signature/Paige_name.png'},
	{id: 'Paradox', label: 'Paradox', portrait: 'portrait/Paradox_card.png', render: 'render/Paradox_Render.png', signature: 'signature/Paradox_name.png'},
	{id: 'Pocket', label: 'Pocket', portrait: 'portrait/Pocket_card.png', render: 'render/Pocket_Render.png', signature: 'signature/Pocket_name.png'},
	{id: 'Rem', label: 'Rem', portrait: 'portrait/Rem_card.png', render: 'render/Rem_Render.png', signature: 'signature/Rem_name.png'},
	{id: 'Seven', label: 'Seven', portrait: 'portrait/Seven_card.png', render: 'render/Seven_Render.png', signature: 'signature/Seven_name.png'},
	{id: 'Shiv', label: 'Shiv', portrait: 'portrait/Shiv_card.png', render: 'render/Shiv_Render.png', signature: 'signature/Shiv_name.png'},
	{id: 'Silver', label: 'Silver', portrait: 'portrait/Silver_card.png', render: 'render/Silver_Render.png', signature: 'signature/Silver_name.png'},
	{id: 'Sinclair', label: 'Sinclair', portrait: 'portrait/Sinclair_card.png', render: 'render/Sinclair_card(1).png', signature: 'signature/Sinclair_name.png'},
	{id: 'Venator', label: 'Venator', portrait: 'portrait/Venator_card.png', render: 'render/Venator_Render.png', signature: 'signature/Venator_name.png'},
	{id: 'Victor', label: 'Victor', portrait: 'portrait/Victor_card.png', render: 'render/Victor_Render.png', signature: 'signature/Victor_name.png'},
	{id: 'Vindicta', label: 'Vindicta', portrait: 'portrait/Vindicta_card.png', render: 'render/Vindicta_Render.png', signature: 'signature/Vindicta_name.png'},
	{id: 'Viscous', label: 'Viscous', portrait: 'portrait/Viscous_card.png', render: 'render/Viscous_Render.png', signature: 'signature/Viscous_name.png'},
	{id: 'Vyper', label: 'Vyper', portrait: 'portrait/Vyper_card.png', render: 'render/Vyper_Render.png', signature: 'signature/Vyper_name.png'},
	{id: 'Warden', label: 'Warden', portrait: 'portrait/Warden_card.png', render: 'render/Warden_Render.png', signature: 'signature/Warden_name.png'},
	{id: 'Wraith', label: 'Wraith', portrait: 'portrait/Wraith_card.png', render: 'render/Wraith_Render.png', signature: 'signature/Wraith_name.png'},
	{id: 'Yamato', label: 'Yamato', portrait: 'portrait/Yamato_card.png', render: 'render/Yamato_Render.png', signature: 'signature/Yamato_name.png'},
];

export {heroAssets};